"""Configuration generator. Slice 437.

Generates annotated, *valid* configuration files:

- ``hugrgate init`` — a starter working directory: ``hugrgate.yaml``
  (daemon config), ``spec.yaml``, ``policy.yaml``,
  ``state.example.yaml``.
- ``hugrgate gen daemon|spec|policy`` — one file at a time, with
  flag-driven customization.

Every generated file round-trips through the real validators
(:class:`DaemonConfig`, :class:`DecisionSpec`,
:func:`policy_from_dict`), so the generator can never emit a file
HugrGate itself rejects. :func:`load_daemon_config` closes the
loop for hand-edited files, and ``hugrgate serve --config`` applies
a config file to the daemon.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from hugrgate.errors import ConfigError, HugrGateError

__all__ = [
    "generate_daemon_config",
    "generate_policy",
    "generate_spec",
    "init_project",
    "load_daemon_config",
    "write_new",
]

_HEADER = "# Generated by `hugrgate gen` (slice 437) — edit freely.\n"


def _dump(header_comment: str, data: dict[str, Any]) -> str:
    return (_HEADER + header_comment
            + yaml.safe_dump(data, default_flow_style=False,
                             sort_keys=False))


# --- daemon config ------------------------------------------------------------

_DAEMON_HEADER = """\
# HugrGate daemon configuration. Keys mirror hugrgate.daemon.DaemonConfig;
# unknown keys are rejected when loading. Apply with:
#   hugrgate serve --config hugrgate.yaml
"""

_DAEMON_DEFAULTS: dict[str, Any] = {
    "host": "127.0.0.1",
    "port": 8377,
    "unix_socket": None,
    "batch_window_ms": 5.0,
    "max_batch": 32,
    "max_queue": 1024,
    "client_policies_path": None,
    "client_id_header": "x-client-id",
    "drain_timeout_s": 10.0,
}


def generate_daemon_config(**overrides: Any) -> str:
    """Render a ``hugrgate.yaml`` daemon config document.

    Overrides are validated against :class:`DaemonConfig` — unknown
    keys and out-of-range values raise :class:`ConfigError` instead
    of producing a file the daemon would reject.
    """
    from hugrgate.daemon import DaemonConfig
    data = dict(_DAEMON_DEFAULTS)
    unknown = set(overrides) - set(data)
    if unknown:
        raise ConfigError(
            f"unknown daemon config key(s): {sorted(unknown)}")
    data.update(overrides)
    try:
        DaemonConfig.from_dict(data)
    except (HugrGateError, ValueError, TypeError, KeyError) as e:
        raise ConfigError(f"invalid daemon config: {e}") from e
    return _dump(_DAEMON_HEADER, data)


def load_daemon_config(path: str | Path) -> Any:
    """Load and validate a daemon config file.

    Raises :class:`ConfigError` on missing files, unparseable YAML,
    unknown keys, or out-of-range values.
    """
    from hugrgate.daemon import DaemonConfig
    p = Path(path)
    try:
        doc = yaml.safe_load(p.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise ConfigError(f"config file not found: {p}") from None
    except yaml.YAMLError as e:
        raise ConfigError(f"config file {p} is not valid YAML: {e}") from e
    if not isinstance(doc, dict):
        raise ConfigError(f"config file {p} must contain a mapping")
    try:
        return DaemonConfig.from_dict(doc)
    except (HugrGateError, ValueError, TypeError, KeyError) as e:
        raise ConfigError(f"invalid daemon config in {p}: {e}") from e


# --- spec ---------------------------------------------------------------------

_SPEC_HEADER = """\
# DecisionSpec template. `type` selects the decision kind:
#   categorical: pick one of `options` (needs >= 2 unique options)
#   binary:      yes/no question in `statement`
#   ordinal:     ordered choice across `levels`
#   numeric:     value within [`minimum`, `maximum`]
"""

_SPEC_FIELDS: dict[str, dict[str, Any]] = {
    "categorical": {"options": ["approve", "escalate", "reject"]},
    "binary": {"statement": "should this request be approved?"},
    "ordinal": {"levels": ["low", "medium", "high"]},
    "numeric": {"minimum": 0.0, "maximum": 100.0},
}


def generate_spec(spec_type: str = "categorical", **fields: Any) -> str:
    """Render a ``spec.yaml`` template for ``spec_type``.

    Extra ``fields`` override the template defaults (e.g.
    ``options=["a", "b"]``). The result is validated with
    :class:`DecisionSpec.from_dict`; invalid combinations raise
    :class:`ConfigError`.
    """
    from hugrgate.spec import DecisionSpec
    if spec_type not in _SPEC_FIELDS:
        raise ConfigError(
            f"unknown spec type {spec_type!r}; expected one of "
            f"{sorted(_SPEC_FIELDS)}")
    data: dict[str, Any] = {"type": spec_type}
    data.update(_SPEC_FIELDS[spec_type])
    data.update(fields)
    try:
        DecisionSpec.from_dict(data)
    except (HugrGateError, ValueError, TypeError, KeyError) as e:
        raise ConfigError(f"invalid spec: {e}") from e
    return _dump(_SPEC_HEADER, data)


# --- policy -------------------------------------------------------------------

_POLICY_HEADER = """\
# DecisionPolicy template. All keys are optional; unknown keys are
# rejected when loading. See hugrgate.serde.policy_from_dict.
"""

_POLICY_DEFAULTS: dict[str, Any] = {
    "minimum_probability": 0.5,
    "maximum_latency_ms": 500.0,
    "remote_inference": False,
    "allowed_backends": None,
    "preferred_backends": None,
    "fallback_behavior": "abstain",
    "privacy_class": "standard",
    "max_cost": None,
    "review_band": None,
}


def generate_policy(**overrides: Any) -> str:
    """Render a ``policy.yaml`` template.

    Overrides are validated with :func:`policy_from_dict`; unknown
    keys raise :class:`ConfigError`.
    """
    from hugrgate.serde import policy_from_dict
    data = dict(_POLICY_DEFAULTS)
    unknown = set(overrides) - set(data)
    if unknown:
        raise ConfigError(
            f"unknown policy key(s): {sorted(unknown)}")
    data.update(overrides)
    try:
        policy_from_dict(data)
    except (HugrGateError, ValueError, TypeError, KeyError) as e:
        raise ConfigError(f"invalid policy: {e}") from e
    return _dump(_POLICY_HEADER, data)


# --- writers -------------------------------------------------------------------

def write_new(path: str | Path, content: str, force: bool = False) -> Path:
    """Write ``content`` to ``path``.

    Refuses to overwrite an existing file unless ``force`` is true
    (:class:`ConfigError`); creates parent directories as needed.
    Returns the written path.
    """
    p = Path(path)
    if p.exists() and not force:
        raise ConfigError(
            f"refusing to overwrite existing file: {p} "
            "(pass --force to overwrite)")
    if p.parent != Path("."):
        p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    return p


def init_project(directory: str | Path = ".",
                 force: bool = False) -> list[Path]:
    """Write a starter HugrGate working directory.

    Creates ``hugrgate.yaml``, ``spec.yaml``, ``policy.yaml`` and
    ``state.example.yaml``. Returns the written paths.
    """
    root = Path(directory)
    written = [
        write_new(root / "hugrgate.yaml", generate_daemon_config(),
                  force=force),
        write_new(root / "spec.yaml", generate_spec(), force=force),
        write_new(root / "policy.yaml", generate_policy(), force=force),
        write_new(root / "state.example.yaml",
                  _HEADER + "# Example decision state — copy to state.yaml "
                           "and fill in.\nfeature_a: 0.7\nfeature_b: 3\n",
                  force=force),
    ]
    return written
