"""Slice 437 — config generator.

Every generated file must round-trip through the real validators;
hand-edited configs load through the same validation; ``serve
--config`` applies a config file with explicit flags winning.
"""

from __future__ import annotations

import pytest
import yaml

from hugrgate.cli import main
from hugrgate.configgen import (
    generate_daemon_config,
    generate_policy,
    generate_spec,
    init_project,
    load_daemon_config,
    write_new,
)
from hugrgate.errors import ConfigError


def test_generate_daemon_config_round_trips():
    text = generate_daemon_config(port=9999, max_batch=8)
    assert text.startswith("# Generated by")
    # parse the YAML ourselves and validate via the real dataclass
    from hugrgate.daemon import DaemonConfig
    doc = yaml.safe_load(text)
    cfg = DaemonConfig.from_dict(doc)
    assert cfg.port == 9999
    assert cfg.max_batch == 8
    assert cfg.host == "127.0.0.1"


def test_generate_daemon_config_rejects_unknown_key():
    with pytest.raises(ConfigError):
        generate_daemon_config(nope=1)


def test_generate_daemon_config_rejects_bad_values():
    with pytest.raises(ConfigError):
        generate_daemon_config(port=99999)


def test_generate_spec_all_types_validate():
    from hugrgate.spec import DecisionSpec
    for spec_type in ("categorical", "binary", "ordinal", "numeric"):
        doc = yaml.safe_load(generate_spec(spec_type))
        DecisionSpec.from_dict(doc)  # must not raise


def test_generate_spec_custom_options():
    from hugrgate.spec import DecisionSpec
    doc = yaml.safe_load(generate_spec("categorical",
                                       options=["a", "b"]))
    assert doc["options"] == ["a", "b"]
    DecisionSpec.from_dict(doc)


def test_generate_spec_rejects_bad_type():
    with pytest.raises(ConfigError):
        generate_spec("quantum")


def test_generate_spec_rejects_invalid_fields():
    with pytest.raises(ConfigError):
        generate_spec("categorical", options=["only-one"])


def test_generate_policy_round_trips():
    from hugrgate.serde import policy_from_dict
    doc = yaml.safe_load(generate_policy(minimum_probability=0.8))
    assert doc["minimum_probability"] == 0.8
    policy = policy_from_dict(doc)
    assert policy.minimum_probability == 0.8


def test_generate_policy_rejects_unknown_key():
    with pytest.raises(ConfigError):
        generate_policy(nope=1)


def test_write_new_refuses_overwrite(tmp_path):
    target = tmp_path / "x.yaml"
    write_new(target, "a: 1\n")
    with pytest.raises(ConfigError):
        write_new(target, "a: 2\n")
    write_new(target, "a: 2\n", force=True)
    assert target.read_text() == "a: 2\n"


def test_load_daemon_config_missing_file(tmp_path):
    with pytest.raises(ConfigError):
        load_daemon_config(tmp_path / "nope.yaml")


def test_load_daemon_config_bad_yaml(tmp_path):
    bad = tmp_path / "bad.yaml"
    bad.write_text("a: [1,\n")
    with pytest.raises(ConfigError):
        load_daemon_config(bad)


def test_load_daemon_config_unknown_key(tmp_path):
    bad = tmp_path / "bad.yaml"
    bad.write_text("nope: 1\n")
    with pytest.raises(ConfigError):
        load_daemon_config(bad)


def test_init_project_writes_four_files(tmp_path):
    written = init_project(tmp_path)
    names = sorted(p.name for p in written)
    assert names == ["hugrgate.yaml", "policy.yaml", "spec.yaml",
                     "state.example.yaml"]
    # everything it wrote must validate
    from hugrgate.daemon import DaemonConfig
    from hugrgate.serde import policy_from_dict
    from hugrgate.spec import DecisionSpec
    DaemonConfig.from_dict(
        yaml.safe_load((tmp_path / "hugrgate.yaml").read_text()))
    DecisionSpec.from_dict(
        yaml.safe_load((tmp_path / "spec.yaml").read_text()))
    policy_from_dict(
        yaml.safe_load((tmp_path / "policy.yaml").read_text()))


def test_init_refuses_without_force(tmp_path):
    init_project(tmp_path)
    with pytest.raises(ConfigError):
        init_project(tmp_path)
    init_project(tmp_path, force=True)  # must not raise


def test_cli_gen_spec(tmp_path, capsys, monkeypatch):
    monkeypatch.chdir(tmp_path)
    assert main(["gen", "spec", "--type", "categorical",
                 "--options", "a,b"]) == 0
    doc = yaml.safe_load((tmp_path / "spec.yaml").read_text())
    assert doc["options"] == ["a", "b"]
    assert "wrote" in capsys.readouterr().out


def test_cli_gen_policy_with_overrides(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    assert main(["gen", "policy", "--min-probability", "0.9",
                 "--out", "p.yaml"]) == 0
    doc = yaml.safe_load((tmp_path / "p.yaml").read_text())
    assert doc["minimum_probability"] == 0.9


def test_cli_gen_daemon(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    assert main(["gen", "daemon"]) == 0
    assert (tmp_path / "hugrgate.yaml").exists()


def test_cli_gen_refuses_overwrite(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    assert main(["gen", "spec"]) == 0
    assert main(["gen", "spec"]) == 2  # ConfigError -> exit 2
    assert main(["gen", "spec", "--force"]) == 0


def test_cli_init(tmp_path, monkeypatch, capsys):
    monkeypatch.chdir(tmp_path)
    assert main(["init", "--dir", "proj"]) == 0
    assert (tmp_path / "proj" / "spec.yaml").exists()
    out = capsys.readouterr().out
    assert "next:" in out


def test_serve_config_overlays_defaults(tmp_path, monkeypatch):
    """serve --config applies the file; explicit flags win."""
    cfg = tmp_path / "hugrgate.yaml"
    cfg.write_text(generate_daemon_config(port=8123, max_batch=4))
    captured = {}

    def fake_daemon(argv):
        captured["argv"] = argv
        return 0

    import hugrgate.daemon
    monkeypatch.setattr(hugrgate.daemon, "main", fake_daemon)
    assert main(["serve", "--config", str(cfg)]) == 0
    argv = captured["argv"]
    assert "--port" in argv
    assert argv[argv.index("--port") + 1] == "8123"
    assert argv[argv.index("--max-batch") + 1] == "4"
    # explicit flag wins over the file
    assert main(["serve", "--config", str(cfg), "--port", "9999"]) == 0
    argv = captured["argv"]
    assert argv[argv.index("--port") + 1] == "9999"


def test_serve_bad_config_is_exit_2(tmp_path):
    bad = tmp_path / "bad.yaml"
    bad.write_text("nope: 1\n")
    assert main(["serve", "--config", str(bad)]) == 2
