"""Edge Intelligence runtime — Campaign VIII (slices 176-200).

A local-first HugrGate extension for ARM64 edge devices (Raspberry Pi,
NVIDIA Jetson, Hailo accelerators, OpenVINO NPUs): platform detection,
resource-aware operating modes, quantized inference, NPU adapter
boundaries, edge-tuned storage/cache/telemetry, benchmarking, fault
injection, and a release gate.

No edge hardware is present in this build environment: every sensor,
accelerator, and board profile is a *testable abstraction* backed by an
injectable mock. Anything that can only be proven on real silicon is
marked ``NEEDS_HARDWARE_VALIDATION`` at the call site and collected in
each slice doc (Execution Law, rule 13).
"""

from __future__ import annotations

from hugrgate.edge.affinity import (
    PROFILES,
    AffinityController,
    EdgeAffinityError,
    parse_cpu_list,
    pin_callable,
)
from hugrgate.edge.bench import (
    ARTIFACT_SCHEMA,
    BenchmarkCase,
    BenchmarkError,
    BenchmarkResult,
    EdgeBenchmark,
    compare_artifacts,
    edge_bench_suite,
    jetson_baseline,
    jetson_bench_suite,
    load_artifact,
    pi_bench_suite,
)
from hugrgate.edge.bootstrap import (
    BootstrapContext,
    BootstrapPlan,
    BootstrapStep,
    OfflineBootstrapError,
    StepOutcome,
    default_edge_plan,
)
from hugrgate.edge.cachetune import (
    DEFAULT_ENTRY_BYTES,
    EdgeCache,
    EdgeCacheConfig,
    EdgeCacheError,
    cache_config_for_board,
    tune_cache,
)
from hugrgate.edge.chaos import (
    BUILTIN_SCENARIOS,
    ChaosResult,
    ChaosRunner,
    FaultScenario,
    build_builtin_runner,
    run_builtin_scenarios,
)
from hugrgate.edge.gate import GATE_CHECKS, GateCheck, GateReport, edge_release_gate
from hugrgate.edge.memory import (
    CRITICAL_AVAILABLE_BYTES,
    LOW_AVAILABLE_BYTES,
    EdgeMemoryError,
    MemoryInfo,
    MemoryManager,
    MemoryMode,
)
from hugrgate.edge.npu import (
    PRECISIONS,
    HailoAdapter,
    JetsonAdapter,
    MockNPUAdapter,
    NPUAdapter,
    NPUCapability,
    NPUError,
    NPURegistry,
    OpenVINOAdapter,
)
from hugrgate.edge.platform import (
    PI_BASELINES,
    Arm64AuditReport,
    Arm64Finding,
    EdgeBaseline,
    PiBoard,
    PlatformInfo,
    PlatformProbe,
    audit_arm64,
    detect_pi_board,
    pi_baseline,
)
from hugrgate.edge.power import (
    MockPowerSource,
    PowerBudget,
    PowerBudgetError,
    PowerSource,
    SysfsPowerSensor,
)
from hugrgate.edge.quant import (
    QUANT_PROFILES,
    Int4Adapter,
    QuantError,
    QuantFormat,
    QuantizedTensor,
    QuantProfile,
    QuantProfileRegistry,
    dequantize_int8,
    estimate,
    int8_matvec,
    int8_roundtrip_error,
    quantize_int8,
    select_profile,
)
from hugrgate.edge.recovery import (
    Checkpoint,
    CheckpointJournal,
    RecoveryError,
)
from hugrgate.edge.residency import (
    ModelEntry,
    ResidencyError,
    ResidencyManager,
)
from hugrgate.edge.routing import (
    THERMAL_CLASSES,
    EdgeRouter,
    edge_cost_of,
)
from hugrgate.edge.storage import (
    DEFAULT_BUFFER_BYTES,
    DEFAULT_MAX_VALUE_BYTES,
    StorageError,
    WearAwareStore,
)
from hugrgate.edge.telemetry import (
    DEFAULT_MAX_EVENTS,
    TelemetryError,
    TelemetryEvent,
    TelemetryLite,
)
from hugrgate.edge.thermal import (
    CRITICAL_C,
    WARN_C,
    MockThermalSensor,
    SysfsThermalSensor,
    ThermalGovernor,
    ThermalLevel,
    ThermalSensor,
    ThermalState,
)
from hugrgate.edge.watchdog import (
    EdgeWatchdog,
    MissPolicy,
    WatchdogError,
)

__all__ = [
    "ARTIFACT_SCHEMA",
    "BUILTIN_SCENARIOS",
    "CRITICAL_AVAILABLE_BYTES",
    "CRITICAL_C",
    "DEFAULT_BUFFER_BYTES",
    "DEFAULT_ENTRY_BYTES",
    "DEFAULT_MAX_EVENTS",
    "DEFAULT_MAX_VALUE_BYTES",
    "GATE_CHECKS",
    "LOW_AVAILABLE_BYTES",
    "PI_BASELINES",
    "PRECISIONS",
    "PROFILES",
    "QUANT_PROFILES",
    "THERMAL_CLASSES",
    "WARN_C",
    "AffinityController",
    "Arm64AuditReport",
    "Arm64Finding",
    "BenchmarkCase",
    "BenchmarkError",
    "BenchmarkResult",
    "BootstrapContext",
    "BootstrapPlan",
    "BootstrapStep",
    "ChaosResult",
    "ChaosRunner",
    "Checkpoint",
    "CheckpointJournal",
    "EdgeAffinityError",
    "EdgeBaseline",
    "EdgeBenchmark",
    "EdgeCache",
    "EdgeCacheConfig",
    "EdgeCacheError",
    "EdgeMemoryError",
    "EdgeRouter",
    "EdgeWatchdog",
    "FaultScenario",
    "GateCheck",
    "GateReport",
    "HailoAdapter",
    "Int4Adapter",
    "JetsonAdapter",
    "MemoryInfo",
    "MemoryManager",
    "MemoryMode",
    "MissPolicy",
    "MockNPUAdapter",
    "MockPowerSource",
    "MockThermalSensor",
    "ModelEntry",
    "NPUAdapter",
    "NPUCapability",
    "NPUError",
    "NPURegistry",
    "OfflineBootstrapError",
    "OpenVINOAdapter",
    "PiBoard",
    "PlatformInfo",
    "PlatformProbe",
    "PowerBudget",
    "PowerBudgetError",
    "PowerSource",
    "QuantError",
    "QuantFormat",
    "QuantProfile",
    "QuantProfileRegistry",
    "QuantizedTensor",
    "RecoveryError",
    "ResidencyError",
    "ResidencyManager",
    "StepOutcome",
    "StorageError",
    "SysfsPowerSensor",
    "SysfsThermalSensor",
    "TelemetryError",
    "TelemetryEvent",
    "TelemetryLite",
    "ThermalGovernor",
    "ThermalLevel",
    "ThermalSensor",
    "ThermalState",
    "WatchdogError",
    "WearAwareStore",
    "audit_arm64",
    "build_builtin_runner",
    "cache_config_for_board",
    "compare_artifacts",
    "default_edge_plan",
    "dequantize_int8",
    "detect_pi_board",
    "edge_bench_suite",
    "edge_cost_of",
    "edge_release_gate",
    "estimate",
    "int8_matvec",
    "int8_roundtrip_error",
    "jetson_baseline",
    "jetson_bench_suite",
    "load_artifact",
    "parse_cpu_list",
    "pi_baseline",
    "pi_bench_suite",
    "pin_callable",
    "quantize_int8",
    "run_builtin_scenarios",
    "select_profile",
    "tune_cache",
]
