#!/usr/bin/env python3
"""Public API inventory generator for HugrGate (Gjallarbrú slice 003).

Introspects every ``hugrgate`` module's explicit ``__all__`` contract
(slice 003 added them everywhere), records each public name's kind and
callable signature, and writes a deterministic inventory to
``docs/campaign-i/003-public-api-inventory.md``.

Run from the repo root with the project venv.
"""

from __future__ import annotations

import importlib
import inspect
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "campaign-i", "003-public-api-inventory.md")

sys.path.insert(0, ROOT)


def iter_modules() -> list[str]:
    mods = []
    pkg = os.path.join(ROOT, "hugrgate")
    for root, dirs, files in os.walk(pkg):
        dirs[:] = sorted(d for d in dirs if d != "__pycache__")
        for f in sorted(files):
            if not f.endswith(".py"):
                continue
            rel = os.path.relpath(os.path.join(root, f), ROOT)[:-3].replace(os.sep, ".")
            mods.append(rel[: -len(".__init__")] if rel.endswith(".__init__") else rel)
    return sorted(mods)


def _stable_repr(obj: object) -> str:
    """Deterministic repr for constants.

    Plain ``repr()`` embeds memory addresses (functions) and
    arbitrary order (sets), which makes the generated inventory
    differ run to run. This renders those stably.
    """
    if inspect.isfunction(obj) or inspect.isbuiltin(obj):
        return f"<function {obj.__qualname__}>"
    if isinstance(obj, dict):
        items = sorted(obj.items(), key=lambda kv: repr(kv[0]))
        inner = ", ".join(
            f"{_stable_repr(k)}: {_stable_repr(v)}" for k, v in items)
        return "{" + inner + "}"
    if isinstance(obj, (set, frozenset)):
        inner = ", ".join(sorted(_stable_repr(v) for v in obj))
        return f"{type(obj).__name__}({{{inner}}})"
    if isinstance(obj, (list, tuple)):
        inner = ", ".join(_stable_repr(v) for v in obj)
        return f"[{inner}]" if isinstance(obj, list) else f"({inner})"
    return re.sub(r"0x[0-9a-fA-F]+", "0x…", repr(obj))


def describe(module, name: str) -> tuple[str, str]:
    obj = getattr(module, name)
    if inspect.isclass(obj):
        kind = "class"
    elif inspect.isfunction(obj) or inspect.isbuiltin(obj):
        kind = "function"
    elif inspect.ismethoddescriptor(obj):
        kind = "method-descriptor"
    else:
        # Determinism: sort set/frozenset constants (iteration order
        # varies with hash seed) and sanitize memory addresses in reprs.
        shown = re.sub(r"0x[0-9a-fA-F]+", "0x…", _stable_repr(obj))
        return "constant", shown[:60]
    try:
        sig = str(inspect.signature(obj))
    except (TypeError, ValueError):
        sig = ""
    return kind, sig


def main() -> int:
    rows: dict[str, list[tuple[str, str, str]]] = {}
    total = 0
    for mod_name in iter_modules():
        module = importlib.import_module(mod_name)
        public = list(getattr(module, "__all__", []))
        entries = []
        for name in public:
            if not hasattr(module, name):
                print(f"ERROR: {mod_name}.__all__ lists missing {name!r}",
                      file=sys.stderr)
                return 1
            kind, sig = describe(module, name)
            entries.append((name, kind, sig))
            total += 1
        rows[mod_name] = entries

    lines = [
        "# Slice 003 — Public API inventory",
        "",
        "Generated by `tools/gen_api_inventory.py` from the live modules'",
        "explicit `__all__` contracts. Re-running on an unchanged tree",
        "yields byte-identical output; `tests/test_api_inventory.py` enforces",
        "that this document never drifts from the code.",
        "",
        f"**Modules:** {len(rows)} · **public names:** {total}",
        "",
        "## API stability policy",
        "",
        "- The package surface (`hugrgate.__all__`) is append-only within a",
        "  major version: names may be added, never silently removed.",
        "- Removing or renaming any name listed below is a breaking change",
        "  and must be announced in `CHANGELOG.md`.",
        "- Underscore-prefixed modules (e.g. `calibration._base`) are",
        "  internal; their `__all__` documents the internal contract only.",
        "",
    ]
    for mod_name, entries in rows.items():
        lines += [
            f"### `{mod_name}`",
            "",
            "| Name | Kind | Signature / value |",
            "|---|---|---|",
        ]
        for name, kind, sig in entries:
            sig_cell = f"`{sig}`" if sig else "—"
            lines.append(f"| `{name}` | {kind} | {sig_cell} |")
        lines.append("")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {OUT} ({len(rows)} modules, {total} public names)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
